name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run tests with coverage
        run: pnpm test:coverage
        env:
          FORCE_COLOR: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build project
        run: pnpm build


